JCF: reverting this commit since it was fixing a problem which went away after Pawel and Pierre helped me properly merge drunc's patch branch code its develop branch code
Revert "JCF: with Pawel's help, fix AttributeError: 'UnifiedShellContext' object has no attribute 'critical' error"

This reverts commit d8e6da82a51818dc8c46eee55a0adb36c0126892.